FROM eclipse-temurin:17-jdk AS build

WORKDIR /app

# Copy only spring project
COPY demo/demo .

RUN chmod +x mvnw
RUN ./mvnw clean package -DskipTests

FROM eclipse-temurin:17-jdk

WORKDIR /app

COPY --from=build /app/target/*.jar app.jar

EXPOSE 8080

CMD ["java", "-jar", "app.jar"]